### ISSUE TITLE
Where I have to put my customization files exactly?

### ISSUE THREAD

**Issue by Lichtjaeger** [claudioc/jingo#137]
Hi,
I have a project folder:

project/
|-.git/
|    |-...
|-node_modules
|    |-...
|-wiki/
|    |-Home.md
|-.gitignore
|-_style.css
|-config.yaml
|-package.json

I use npm to start jingo with `npm start` ("jingo -c ./config.yaml").

My configuration:

```
application:
  repository: '.'
  docSubdir: 'wiki'
customizations:
  sidebar: _sidebar.md
  footer: _footer.md
  style: _style.css
  script: _script.js
```

But my _style.css isn't loading. What I have to configure or where I have to put it. I have tried the wiki directory, but it didn't work.
