### ISSUE TITLE
Error with multiple local-accounts.

### ISSUE THREAD

**Issue by chriskvik** [claudioc/jingo#168]
Hi, I may be doing this the wrong way but my limited YAML-knowledge combined with some Google-fu gave me the following config for multiple-local users accounts.
<pre>
 local:
    enabled: true
    accounts:
      - username: 'user1'
        passwordHash: 'longhash'
        email: 'user@gmail.com'
      - username: 'user2'
        passwordHash: 'longhash'
        email: 'user@gmail.com'
</pre>

And jingo says : 
Sep 17 12:06:24 utils systemd[1]: Started Wiki.
Sep 17 12:06:24 utils jingo[1941]: Error: Unrecognized section name(s) email

**Comment by claudioc** [comment]
Mmmh, interesting because I cannot reproduce this problem.

My authentication section reads like this:

```yaml
authentication:
  google:
    enabled: true
    clientId: "somethins.apps.googleusercontent.com"
    clientSecret: "V1q9SW2CszheuYT9-5CJ7acg"
  github:
    enabled: false
    clientId: replace me with the real value
    clientSecret: replace me with the real value
  local:
    enabled: true
    accounts:
      - username: 'one'
        passwordHash: 'zyx'
        email: 'some1@example.com'
      - username: 'two'
        passwordHash: 'xyz'
        email: 'some2@example.com'
```
