### ISSUE TITLE
can't use wiki after login via local authorization

### ISSUE THREAD

**Issue by lifeisdream** [claudioc/jingo#248]
![image](https://user-images.githubusercontent.com/1473995/45580688-bf60c800-b89c-11e8-8d4a-b8b0b890d02d.png)

![image](https://user-images.githubusercontent.com/1473995/45580702-db646980-b89c-11e8-99e8-fb5ce21e56ee.png)

**Comment by lifeisdream** [comment]
Use os x and absolute path for git repo 

`repository: '/Users/owl/imperial-lab/wjs_imperial_lab/repo'`

**Comment by claudioc** [comment]
Hi,

I just installed a fresh copy of Jingo with a new local repo and local authentication. I have been able to create the home page, and another page below it.

This is my configuration (straight for `jingo -s`, changing the auth and the repo):

```
# Configuration sample file for Jingo (YAML)
application:
  title: Jingo
  logo: ""
  favicon: ""
  repository: "/Users/claudioc/Documents/jingo"
  docSubdir: ""
  remote: ""
  pushInterval: 30
  secret: change me
  git: git
  skipGitCheck: false
  loggingMode: 1
  pedanticMarkdown: true
  gfmBreaks: true
  staticWhitelist: '/\.png$/i, /\.jpg$/i, /\.gif$/i'
  proxyPath: ""
authentication:
  google:
    enabled: false
    clientId: replace me with the real value
    clientSecret: replace me with the real value
    redirectURL: ""
  github:
    enabled: false
    clientId: replace me with the real value
    clientSecret: replace me with the real value
    redirectURL: ""
  ldap:
    enabled: false
    url: "ldap://example.org:389"
    bindDn: ""
    bindCredentials: ""
    searchBase: "ou=people,dc=example,dc=org"
    searchFilter: "(uid={{username}})"
    searchAttributes: ""
  local:
    enabled: true
    accounts:
      - username: "claudioc"
        passwordHash: "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3"
        email: "claudio.cicali@gmail.com"
features:
  markitup: false
  codemirror: true
  gravatar: true
server:
  hostname: localhost
  port: 6067
  localOnly: false
  baseUrl: ""
  CORS:
    enabled: false
    allowedOrigin: "*"
authorization:
  anonRead: true
  validMatches: .+
  emptyEmailMatches: false
pages:
  index: Home
  title:
    fromFilename: true
    fromContent: false
    asciiOnly: false
    lowercase: false
  itemsPerPage: 10
customizations:
  sidebar: _sidebar.md
  footer: _footer.md
  style: _style.css
  script: _script.js
```
